name: Build Image

on:
  pull_request: { branches: [ "main" ] }
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build-pr:
    name: "PR"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2.7.0

  build-main:
    name: "main"
    if: github.event_name == 'push' && contains(github.ref, '/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  build-tag:
    name: "tag"
    if: github.event_name == 'push' && contains(github.ref, '/tags/v')
    runs-on: ubuntu-latest
    steps:
      - id: generate-version
        env: { github_ref: "${{github.ref_name }}" }
        run: echo "::set-output name=ver::$(echo $github_ref | cut -c2-)"
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.generate-version.outputs.ver }}
